[versions]
# libraries
android = "4.1.1.4"
jetty = "11.0.25"
junit4 = "4.13.2"
slf4j = "2.0.17"
logback = "1.5.18"
jackson = "2.19.0"
aws = "2.31.35"
kotlin = "2.2.21"
commons-text = "1.13.1"
commons-io = "2.19.0"
httpclient5 = "5.4.4"
guava = "33.4.8-jre"
gson = "2.13.1"
hsqldb = "2.7.4"
antlr = "4.13.2"
asm = "9.8"
kotlinx-coroutines = "1.10.2"
kotlinx-collections-immutable = "0.3.8"
mockito = "5.17.0"
flexmark = "0.64.8"
h2 = "2.3.232"
scala = "2.13.16"
groovy = "3.0.19" # IntelliJ IDEA 2023.2 uses Groovy 3.0.19
jsoup = "1.20.1"
monteMedia = "17.2.1"
selenium = "4.32.0"
webdrivermanager = "6.1.0"
remoterobot = "0.11.24.506"
okhttp = "4.12.0"
batik = "1.18"
commonsLang3 = "3.17.0"
diffutils = "1.3.0"
swaggerAnnotations = "1.6.15"
jsr305 = "3.0.2"
jacksonDatabindNullable = "0.2.6"
jakartaAnnotationsApi = "3.0.0"
jtransforms = "1.3.10"
scalaJava8Compat = "1.0.2"
graalvm = "24.2.1"
eclipseJdtCore = "3.41.0"
pdfbox = "3.0.5"
zxing = "3.5.3"
poi = "5.4.1"
googleApiClient = "2.7.2"
googleOauthClientJetty = "1.39.0"
googleApiServicesOauth2 = "v2-rev20200213-2.0.0"
googleHttpClientGson = "1.47.0"
commonsCodec = "1.18.0"
commonsCsv = "1.10.0"
odftoolkit = "0.12.0"
androidx-core = "1.17.0"
androidx-lifecycle = "2.9.4"
androidx-activity = "1.11.0"
androidx-appcompat = "1.7.1"
material = "1.13.0"
androidx-constraintlayout = "2.2.1"
androidx-swiperefreshlayout = "1.1.0"
androidx-webkit = "1.14.0"
androidx-emoji2 = "1.6.0"
slf4jandroid = "1.7.36"
androidx-test-ext = "1.3.0"
androidx-test-espresso = "3.7.0"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.9.0"
kover = "0.9.1"
qodana = "2025.1.0"
shadow = "8.1.1"
junitJupiter = "5.13.2"

[libraries]
android = { module = "com.google.android:android", version.ref = "android" }
jetty-server = { group = "org.eclipse.jetty", name = "jetty-server", version.ref = "jetty" }
jetty-webapp = { group = "org.eclipse.jetty", name = "jetty-webapp", version.ref = "jetty" }
jetty-websocket-servlet = { group = "org.eclipse.jetty.websocket", name = "websocket-servlet", version.ref = "jetty" }
jetty-websocket-server = { group = "org.eclipse.jetty.websocket", name = "websocket-jetty-server", version.ref = "jetty" }
jetty-websocket-client = { group = "org.eclipse.jetty.websocket", name = "websocket-jetty-client", version.ref = "jetty" }
jetty-servlet = { group = "org.eclipse.jetty", name = "jetty-servlet", version.ref = "jetty" }
jetty-annotations = { group = "org.eclipse.jetty", name = "jetty-annotations", version.ref = "jetty" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson-jaxrs-json = { group = "com.fasterxml.jackson.jaxrs", name = "jackson-jaxrs-json-provider", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
aws-sdk = { group = "software.amazon.awssdk", name = "aws-sdk-java", version.ref = "aws" }
aws-bedrock = { group = "software.amazon.awssdk", name = "bedrock", version.ref = "aws" }
aws-bedrockruntime = { group = "software.amazon.awssdk", name = "bedrockruntime", version.ref = "aws" }
aws-s3 = { group = "software.amazon.awssdk", name = "s3", version.ref = "aws" }
aws-kms = { group = "software.amazon.awssdk", name = "kms", version.ref = "aws" }
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
httpclient5 = { group = "org.apache.httpcomponents.client5", name = "httpclient5", version.ref = "httpclient5" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hsqldb = { group = "org.hsqldb", name = "hsqldb", version.ref = "hsqldb" }
antlr-runtime = { group = "org.antlr", name = "antlr4-runtime", version.ref = "antlr" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
antlr-tool = { group = "org.antlr", name = "antlr4", version.ref = "antlr" } # For antlr plugin
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
flexmark-all = { group = "com.vladsch.flexmark", name = "flexmark-all", version.ref = "flexmark" }
flexmark-core = { group = "com.vladsch.flexmark", name = "flexmark", version.ref = "flexmark" }
flexmark-ext-tables = { group = "com.vladsch.flexmark", name = "flexmark-ext-tables", version.ref = "flexmark" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
scala-library = { group = "org.scala-lang", name = "scala-library", version.ref = "scala" }
scala-compiler = { group = "org.scala-lang", name = "scala-compiler", version.ref = "scala" }
scala-reflect = { group = "org.scala-lang", name = "scala-reflect", version.ref = "scala" }
groovy-all = { group = "org.codehaus.groovy", name = "groovy-all", version.ref = "groovy" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
monte-media-screenrecorder = { group = "ch.randelshofer", name = "org.monte.media.screenrecorder", version.ref = "monteMedia" }
monte-media = { group = "ch.randelshofer", name = "org.monte.media", version.ref = "monteMedia" }
monte-media-swing = { group = "ch.randelshofer", name = "org.monte.media.swing", version.ref = "monteMedia" }
selenium-java = { group = "org.seleniumhq.selenium", name = "selenium-java", version.ref = "selenium" }
webdrivermanager = { group = "io.github.bonigarcia", name = "webdrivermanager", version.ref = "webdrivermanager" }
remoterobot-fixtures = { group = "com.intellij.remoterobot", name = "remote-fixtures", version.ref = "remoterobot" }
remoterobot-robot = { group = "com.intellij.remoterobot", name = "remote-robot", version.ref = "remoterobot" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
batik-transcoder = { group = "org.apache.xmlgraphics", name = "batik-transcoder", version.ref = "batik" }
batik-codec = { group = "org.apache.xmlgraphics", name = "batik-codec", version.ref = "batik" }
httpclient5-fluent = { group = "org.apache.httpcomponents.client5", name = "httpclient5-fluent", version.ref = "httpclient5" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang3" }
diffutils = { group = "com.googlecode.java-diff-utils", name = "diffutils", version.ref = "diffutils" }
swagger-annotations = { group = "io.swagger", name = "swagger-annotations", version.ref = "swaggerAnnotations" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
jackson-databind-nullable = { group = "org.openapitools", name = "jackson-databind-nullable", version.ref = "jacksonDatabindNullable" }
jakarta-annotations-api = { group = "jakarta.annotation", name = "jakarta.annotation-api", version.ref = "jakartaAnnotationsApi" }
aws-auth = { group = "software.amazon.awssdk", name = "auth", version.ref = "aws" }
aws-sso = { group = "software.amazon.awssdk", name = "sso", version.ref = "aws" }
jtransforms = { group = "org.openimaj", name = "JTransforms", version.ref = "jtransforms" }
scala-java8-compat = { group = "org.scala-lang.modules", name = "scala-java8-compat_2.13", version.ref = "scalaJava8Compat" }
graalvm-js = { group = "org.graalvm.js", name = "js", version.ref = "graalvm" }
graalvm-js-language = { group = "org.graalvm.js", name = "js-language", version.ref = "graalvm" }
eclipse-jdt-core = { group = "org.eclipse.jdt", name = "org.eclipse.jdt.core", version.ref = "eclipseJdtCore" }
pdfbox = { group = "org.apache.pdfbox", name = "pdfbox", version.ref = "pdfbox" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
poi = { group = "org.apache.poi", name = "poi", version.ref = "poi" }
poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "poi" }
poiscratchpad = { group = "org.apache.poi", name = "poi-scratchpad", version.ref = "poi" }
zxing-javase = { group = "com.google.zxing", name = "javase", version.ref = "zxing" }
google-api-client = { group = "com.google.api-client", name = "google-api-client", version.ref = "googleApiClient" }
google-oauth-client-jetty = { group = "com.google.oauth-client", name = "google-oauth-client-jetty", version.ref = "googleOauthClientJetty" }
google-api-services-oauth2 = { group = "com.google.apis", name = "google-api-services-oauth2", version.ref = "googleApiServicesOauth2" }
google-http-client-gson = { group = "com.google.http-client", name = "google-http-client-gson", version.ref = "googleHttpClientGson" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commonsCodec" }
commons-csv = { group = "org.apache.commons", name = "commons-csv", version.ref = "commonsCsv" }
odfdom-java = { group = "org.odftoolkit", name = "odfdom-java", version.ref = "odftoolkit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "androidx-webkit" }
androidx-emoji2 = { group = "androidx.emoji2", name = "emoji2", version.ref = "androidx-emoji2" }
androidx-emoji2-bundled = { group = "androidx.emoji2", name = "emoji2-bundled", version.ref = "androidx-emoji2" }
slf4jandroid = { group = "org.slf4j", name = "slf4j-android", version.ref = "slf4jandroid" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junitJupiter" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit4" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
kotlin-script-runtime = { group = "org.jetbrains.kotlin", name = "kotlin-script-runtime", version.ref = "kotlin" }
aws-bom = { group = "software.amazon.awssdk", name = "bom", version.ref = "aws" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }